kind: Deployment
apiVersion: extensions/v1beta1
…
template:
  spec:
    containers:
      - name: PodA
        image: busybox:1.28
        resources:
          limits:
            memory: 400Mi
            cpu: 1
          requests:
            memory: 400Mi
            cpu: 400m
      - name: PodB
        image: busybox:1.28
        resources:
          limits:
            memory: 200Mi
            cpu: 1
          requests:
            memory: 200Mi
            cpu: 200m
      - name: PodC
        image: busybox:1.28
        resources:
          limits:
            memory: 400Mi
            cpu: 1
          requests:
            memory: 400Mi

